name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies for generate data
      run: npm ci
      working-directory: generate-data
      
    - name: Generate data
      run: npm run generate
      working-directory: generate-data

    - name: Install dependencies for web site
      run: npm ci
      working-directory: 3d-printer-for-hobbies-app

    - name: Build
      run: npm run build -- --base-href=/3d-printers-for-hobbies/
      working-directory: 3d-printer-for-hobbies-app

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: 3d-printer-for-hobbies-app/dist/3d-printer-for-hobbies-app
        enable_jekyll: true
